### ISSUE TITLE
Open TODO list

### ISSUE THREAD

**Issue by aescande** [jrl-umi3218/jrl-umi3218.github.com#70]
This a list of small and big things to do to enhance the website, Anyone is welcome to pick up an item to work on.

- [ ] Linking the github, youtube and mc-rtc website to the main page
- [ ] Adding the new JRL logo
- [ ] Having a real English/Japanese dual language version

**Comment by rohanpsingh** [comment]
- [ ] Create a "Join Us" page.

**Comment by fkanehiro** [comment]
>Having a real English/Japanese dual language version

@gergondet 
Can you please consider to do this as you did for the mc_rtc website?
